### ISSUE TITLE
Error processing the Account list views - undefined error

### ISSUE THREAD

**Issue by ar-chen** [tomansley/SimpliListViews#167]
**Describe the bug**
Our users are getting a Error processing the Account list views - undefined error

**Simpli List View Version**
Most updated, installed for All Users
**To Reproduce**
1. Go to the account single object list view
2. Click the refresh button
3. Below error pops up 

**Expected behavior**
I expected the account list views to refresh

**Screenshots**

![Image](https://github.com/user-attachments/assets/930db0d2-da5d-4523-abea-a4407d69cb2d)

**Desktop (please complete the following information):**
Chrome

**Additional context**

**Comment by tomansley** [comment]
Hello,

I am assuming that you have managed to resolve the permissions issues you
were having previously. Updating the list view obviously requires write
access to the simpli_lv__List_View__c table. Does the user have the
permissions?

If you believe permissions to be correct then we will need to debug. Please
turn on debugging using this FAQ -
https://github.com/tomansley/SimpliListViews/wiki/FAQ#how-do-i-turn-debugging-on-and-off-1

Once debugging is on rerun the users request and see if any logs show
anything that might need attention.

Also, sometimes the errors are displayed in the browser javascript console.

Let me know if you are able to make progress.

Cheers
Tom

**Comment by tomansley** [comment]
I just read a bit more on your additional context. Unfortunately the Simpli List View User is not able to refresh the list views as they do not have EDIT ALL permissions which is needed as the records are not owned by the user.

Adjust the permission set to allow EDIT ALL for the user and this should resolve the issue.

**Comment by ar-chen** [comment]
Are you saying they need edit all access on the Account object itself? This would completely override our current sharing model and how we are defining record access. I granted modify all records on the list view object itself, but I'm still getting the same error. 

What I don't understand is why my other users are able to refresh the list views on a custom object Bonus_Offer__c that we have, but why the rest of our users are unable to refresh the list views on the Account object and get that error shown above.

**Comment by tomansley** [comment]
No, they need edit all on simpli_lv__List_View__c object.

The reason why sys admins are able to is because they have that permission.

**Comment by ar-chen** [comment]
They literally have access to them all already and they're still getting the error, which is why I'm confused. I don't get why we're having so many access issues even with the right permission sets and object settings configured. 

![Image](https://github.com/user-attachments/assets/e601c0f7-7327-425f-b4bc-f633df676f07)

**Comment by tomansley** [comment]
Try one thing for me.

Go into setup -> Platform Cache -> simpliListViews. And clear the cache, then try again.

This is very strange. I am wondering if this is a caching issue.
________________________________

**Comment by ar-chen** [comment]
Still getting the same error after clearing platform cache. Not sure what else to do at this point.

**Comment by tomansley** [comment]
We will get this resolved.

Let me take a look and make sure I can refresh on a single list view. Hopefully I can reproduce.

Will get back to you
________________________________

**Comment by tomansley** [comment]
Ok, so I have created a standard user which uses the standard profile. I did two things - 

1. I gave the user the "Simpli List Views User" permission set.
2. I updated the standard profile to include the ability to Edit All list views.

![Image](https://github.com/user-attachments/assets/bd2f52bf-c69b-4c16-8a6b-66d3e821e5ef)

This worked. The user was able to see a Single List View and update it.

Any thoughts on those profile settings and permission set?

**Comment by tomansley** [comment]
Also, just to make sure....the users need FIELD ACCESS to all the fields on the simpli_lv_List_View__c object as well. I am guessing you provided those permissions but just checking.

![Image](https://github.com/user-attachments/assets/303f0000-cd4b-412a-83b5-6044fb042551)

**Comment by ar-chen** [comment]
They have field access to all of the above and when I removed the create permission from List Views, I got a no access to entity simpli_LV_List_View__c instead. Once I added create permission back, I got the same Error processing the Account list views - undefined error. 

This is affecting all our users and we need a solution asap please.

**Comment by tomansley** [comment]
Does it only happen with one specific list view? Or does it happen with any
list view that a user tries to update?

**Comment by tomansley** [comment]
Ok, that is helpful.

But I am confused and want to make sure I have the issue right. You are saying that the issue is when a user wants to update the ListviewAnything list view because the original list view has changed....correct?

Are users changing the salesforce list views that much?

Or, are they trying to make changes to the ListviewAnything list view by clicking on the cog icon on the top right? So things like conditional highlighting etc.


________________________________

**Comment by ar-chen** [comment]
![Image](https://github.com/user-attachments/assets/70fdec59-0121-43e6-ab6d-c31758b67722)

They get the issue when they try to update the list view anything list view because the original list has changed so they want to refresh it and make sure that their list populates and they can select the right list view.

**Comment by ar-chen** [comment]
We have a lot of list views for Account yes

How do they find the list view they want and update only that list view? 

These users are creating new list views and they won't be visible in the Select List View list unless they click the refresh button no?

Once they have a created list view, are you saying you can update one list view instead of every single account list view by selecting the one they want to update in the Select List View and then clicking refresh?

**Comment by tomansley** [comment]
Ok, interesting. I get your issue.

I haven't had anyone using the app that creates list views so frequently that this is a problem.

So two things -

1. There is a feature on the admin page to allow you to schedule updating list views at intervals. You can set this if it helps. I don't know how many lost views you have total but I wouldn't set it more than every hour or so.

2. I will update the list view update button so that it can handle lots of list views. This will take me a few days but I will get you a new package as soon possible.

You could also delete unused account list views to try and reduce the number processed so that it doesn't hit the governor limit.

Make sense?
________________________________

**Comment by tomansley** [comment]
I have updated the package to allow large numbers of list views to be
updated from one object. If more than 50 list views exist on the object a
batch job is started and the user is shown the progress of the updates.

[image: image.png]

If there are less than 50 the updates are done immediately.

Try installing this package -
https://<YOUR_SALESFORCE_URL>/packaging/installPackage.apexp?p0=04tKY000000kdjS

It would be best to install in a sandbox and test if possible as I may have
made a mistake by accident.

Let me know ifthis solves your issue.

Cheers
Tom

**Comment by ar-chen** [comment]
Thanks for the quick turnaround, will try this out and let you know.

**Comment by ar-chen** [comment]
I'm still getting the same error as above.

Error processing the Account list views - undefined error

**Comment by tomansley** [comment]
ok, we need to take a step back and get more logging so that I can identify
the issue more clearly.

I will update the package to provide more logging as "undefined" is
useless! Then we install that package and rerun to hopefully get a better
picture of the issue.

I'll be in touch hopefully in a little bit.

**Comment by tomansley** [comment]
Ok, install this -
https://<YOUR_SFDC_URL>/installPackage.apexp?p0=04tKY000000kdnk

It will fail. When it does a better error should be displayed. If it does
not right click on the page and select "Inspect" then look for the console.
Check the output and let me know of any errors.

[image: image.png]

**Comment by ar-chen** [comment]
This link doesn't work. I got an invalid link error. 

![Image](https://github.com/user-attachments/assets/2a8e5bd7-b6a3-4b70-a5d6-71a828a97ac3)

**Comment by ar-chen** [comment]
<img width="558" alt="Image" src="https://github.com/user-attachments/assets/11c2949b-f092-48ca-ad14-e7836487e10d" />

<img width="558" alt="Image" src="https://github.com/user-attachments/assets/ae0957ce-1a2d-41e6-b96c-7346ed1ab117" />

Not sure what these errors are

**Comment by tomansley** [comment]
There should be more. You need to scroll down to the bottom

**Comment by ar-chen** [comment]
I've scrolled to the bottom of the console on both and don't see any more errors. Not sure what you mean exactly. Are we able to connect on a call or something?

**Comment by tomansley** [comment]
Yea, I think we will need to connect. My email is ***@***.*** Please send me an email and we can set up a time to chat


________________________________

**Comment by ar-chen** [comment]
I don't see your email. It is blurred out.

**Comment by tomansley** [comment]
tom at ansleyllc dot com

Better?
________________________________

**Comment by ar-chen** [comment]
My other users who didn't have issues before are now running into issues. This user received this undefined error after selecting a specific list view and trying to refresh it. Any idea why? I also didn't see an exception under him either so I wasn't able to get more context.

![Image](https://github.com/user-attachments/assets/530235dd-756e-4c6f-8308-91ea1b1a2e0d)

**Comment by tomansley** [comment]
Great! We are going backwards.

Please run this in dev console -

Select count(id) from listview where sobjecttype = 'Account'

What's the count?

I need to reproduce this issue in my org to fix it once and for all. I'll start on that and see where we get.

________________________________

**Comment by ar-chen** [comment]
Total count is 33.

**Comment by tomansley** [comment]
Hi Arthur,

That number is quite low. It should be able to process those without a
problem. I was expecting there to be perhaps hundreds of list views for the
Account.

I may need to hop on another call with you to have a look at a few things.
Do you have time today?

Cheers
Tom

**Comment by ar-chen** [comment]
Yes, I have time now until 10 am PST and also between 11:30 am-12:00 pm PST and also anytime after 1 pm PST. Please let me know what works and I'll send out an invite again.

**Comment by ar-chen** [comment]
I got the error again after having a user try it. Not sure why it's randomly working and then not working again.

<img width="1439" alt="Image" src="https://github.com/user-attachments/assets/81ebb15c-9edf-4d33-b8d3-bf3ee743a2cb" />

**Comment by ar-chen** [comment]
<img width="947" alt="Image" src="https://github.com/user-attachments/assets/d611a452-8637-4f89-a9a4-15d6f64036f7" />
This is the error I got earlier today and what I got from the exception logs.

Now when testing with him again it works. 

<img width="1114" alt="Image" src="https://github.com/user-attachments/assets/37627410-b3eb-422e-b960-33274bbaf367" />

But when testing earlier today it didn't so it appears that it is randomly working from time to time. Every time Victor has tried it's failed though. Not sure if there's anything to do with login as a user as a system admin.

**Comment by tomansley** [comment]
Arthur,

Please install this latest package and see if it resolves your user issues - https://<YOUR_SFDC_<https://login.salesforce.com/packaging/installPackage.apexp?p0=04tKY000000keqG>URL>/packaging/installPackage.apexp?p0=04tKY000000keqG<https://login.salesforce.com/packaging/installPackage.apexp?p0=04tKY000000keqG>

One thing to note - I came to realize that in order for users to be able to perform reprocessing of list views they needed to be able to both modify and create list view objects. So I put a check in for the user and if they are not able to do that then the list view reprocessing button isn't even displayed. By default this will be the case because unless explicitly set we don't want users with that access.

So, if they just have the Simpli List Views User permission set they will NOT be able to reprocess.

In order to reprocess you will.....in some way.....give them the ability to MODIFY ALL RECORDS and CREATE on the List View object. The button should then appear as expected.

Let me know what you find. This issue has been a slippery one so I am not even sure if it will solve the issue! Fingers crossed.

Thanks for the patience whilst I work through getting this resolved.

Cheers
Tom

________________________________

**Comment by tomansley** [comment]
Hold off. That package is bad. Creating another one to send in a bit.


________________________________

**Comment by tomansley** [comment]
Use this one -
https://<YOUR_SFDC_URL>/packaging/installPackage.apexp?p0=04tKY000000keqQ
